### ISSUE TITLE
why not just rename the existing repo?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [rakyll/hey#2]

**Comment by rakyll** [comment]
Not to break the existing users.

```
go get github.com/rakyll/boom
```

will install a binary called `hey`. All the existing programs and scripts shelling out to boom will be broken. Silently breaking things might not be ideal. Once we put a notice in the binary, they will eventually move off of the old one.

A new repo means all the Github history (bugs, PRs, stars, watchers) will be gone. Bugs and PRs can be migrated. I am not sure I should prioritize keeping watchers and stars, so a new repo doesn't sound like a bad idea.

**Comment by ahmetalpbalkan** [comment]
Hmm if you really think users people made it part of their unattended build infra or something, well, they probably should've vendored it locally already? I would totally keep the existing repo for the sake of PR/issues history as well as stars, but I respect your opinion too. :)

**Comment by rakyll** [comment]
We will keep the existing repo around for a very long time for those who is depending on the local copies of the tool.

The issue list should be migrated once it is triaged. The sample applies for the PRs, many of them are outdated because I had no time to maintain the project and it was mainly working fine.
