### ISSUE TITLE
Unable to generate report from hey

### ISSUE THREAD

**Issue by PrateekJoshi** [rakyll/hey#218]
No report is being generated by using `-o` flag as mentioned in the README file. I am using Linux x86_64 machine. 

![image](https://user-images.githubusercontent.com/10491056/91018703-89dac280-e60d-11ea-9a26-6147238f6839.png)

Please let me know if any more details are required.

**Comment by k8scommander** [comment]
You're using the -o wrong, instead of giving it a file, it gets an output type, supports only csv at the moment.
`./hey  -c 10 -m GET -o csv https://yourtest_url`

_will output this instead of the summery:_

response-time,DNS+dialup,DNS,Request-write,Response-delay,Response-read,status-code,offset
0.0155,0.0116,0.0003,0.0001,0.0016,0.0021,200,0.0005
0.0181,0.0135,0.0004,0.0000,0.0020,0.0025,200,0.0002
0.0180,0.0135,0.0004,0.0000,0.0020,0.0025,200,0.0004
0.0182,0.0134,0.0004,0.0001,0.0019,0.0028,200,0.0003
0.0183,0.0134,0.0005,0.0000,0.0019,0.0028,200,0.0004
0.0189,0.0136,0.0006,0.0000,0.0028,0.0024,200,0.0002
0.0190,0.0138,0.0005,0.0000,0.0015,0.0034,200,0.0002
0.0195,0.0136,0.0005,0.0000,0.0037,0.0021,200,0.0003
0.0041,0.0000,0.0000,0.0000,0.0019,0.0022,200,0.0160
0.0198,0.0134,0.0005,0.0000,0.0029,0.0035,200,0.0005
0.0214,0.0135,0.0004,0.0001,0.0050,0.0028,200,0.0006
