### ISSUE TITLE
Is there a memory leak in hey?

### ISSUE THREAD

**Issue by psy-core** [rakyll/hey#73]
I use hey for http api presure test with parameters:
    `-n 1260000000 -m POST -D file -c 500`
and find it consumes a lot of memories:
```
17-11-17_14:18:28    23440 iflyweb 20 0 20.760g 9.869g 3048 S 206.7 31.6 7:02.09 hey
17-11-17_14:18:29    23440 iflyweb 20 0 20.760g 9.877g 3048 S 220.0 31.6 7:04.60 hey
17-11-17_14:18:30    23440 iflyweb 20 0 20.760g 9.882g 3048 S 220.0 31.6 7:07.05 hey
17-11-17_14:18:31    23440 iflyweb 20 0 20.760g 9.885g 3048 S 237.5 31.6 7:09.75 hey
17-11-17_14:18:32    23440 iflyweb 20 0 20.760g 9.890g 3048 S 226.7 31.6 7:12.26 hey
17-11-17_14:18:33    23440 iflyweb 20 0 20.760g 9.893g 3048 S 220.0 31.7 7:14.78 hey
17-11-17_14:18:35    23440 iflyweb 20 0 20.760g 9.896g 3048 S 226.7 31.7 7:17.23 hey
17-11-17_14:18:36    23440 iflyweb 20 0 20.760g 9.904g 3048 S 233.3 31.7 7:19.70 hey
17-11-17_14:18:37    23440 iflyweb 20 0 20.760g 9.905g 3048 S 240.0 31.7 7:22.26 hey
17-11-17_14:18:38    23440 iflyweb 20 0 20.760g 9.907g 3048 S 253.3 31.7 7:24.97 hey
17-11-17_14:18:39    23440 iflyweb 20 0 20.760g 9.909g 3048 S 273.3 31.7 7:27.75 hey
17-11-17_14:18:40    23440 iflyweb 20 0 20.760g 9.913g 3048 S 246.7 31.7 7:30.66 hey
17-11-17_14:18:42    23440 iflyweb 20 0 20.760g 9.914g 3048 S 226.7 31.7 7:33.32 hey
17-11-17_14:18:43    23440 iflyweb 20 0 20.760g 9.916g 3048 S 212.5 31.7 7:36.13 hey
17-11-17_14:18:44    23440 iflyweb 20 0 20.760g 9.921g 3048 S 233.3 31.7 7:38.94 hey
17-11-17_14:18:45    23440 iflyweb 20 0 20.760g 9.924g 3048 S 231.2 31.8 7:41.72 hey
17-11-17_14:18:46    23440 iflyweb 20 0 20.760g 9.926g 3048 S 240.0 31.8 7:44.41 hey
17-11-17_14:18:47    23440 iflyweb 20 0 20.760g 9.927g 3048 S 233.3 31.8 7:47.26 hey
17-11-17_14:18:49    23440 iflyweb 20 0 20.760g 9.930g 3048 S 240.0 31.8 7:50.16 hey
17-11-17_14:18:50    23440 iflyweb 20 0 20.760g 9.931g 3048 S 246.7 31.8 7:53.09 hey
17-11-17_14:18:51    23440 iflyweb 20 0 20.761g 9.934g 3048 S 240.0 31.8 7:55.92 hey
17-11-17_14:18:52    23440 iflyweb 20 0 20.761g 9.938g 3048 S 266.7 31.8 7:58.75 hey
17-11-17_14:18:53    23440 iflyweb 20 0 20.761g 9.939g 3048 S 253.3 31.8 8:01.63 hey
17-11-17_14:18:54    23440 iflyweb 20 0 20.762g 9.943g 3048 S 246.7 31.8 8:04.54 hey
17-11-17_14:18:55    23440 iflyweb 20 0 20.762g 9.952g 3048 S 253.3 31.8 8:07.53 hey
17-11-17_14:18:57    23440 iflyweb 20 0 20.762g 9.958g 3048 S 226.7 31.9 8:10.49 hey
17-11-17_14:18:58    23440 iflyweb 20 0 20.762g 9.959g 3048 S 246.7 31.9 8:13.53 hey
17-11-17_14:18:59    23440 iflyweb 20 0 20.763g 9.961g 3048 S 253.3 31.9 8:16.28 hey
17-11-17_14:19:00    23440 iflyweb 20 0 20.763g 9.971g 3048 S 240.0 31.9 8:19.11 hey
17-11-17_14:19:01    23440 iflyweb 20 0 20.763g 9.978g 3048 S 240.0 31.9 8:21.90 hey
17-11-17_14:19:02    23440 iflyweb 20 0 20.764g 9.993g 3048 S 218.8 32.0 8:24.84 hey
17-11-17_14:19:04    23440 iflyweb 20 0 20.764g 0.010t 3048 S 233.3 32.0 8:27.57 hey
17-11-17_14:19:05    23440 iflyweb 20 0 20.764g 0.010t 3048 S 200.0 32.0 8:30.19 hey
17-11-17_14:19:06    23440 iflyweb 20 0 20.765g 0.010t 3048 S 193.3 32.1 8:32.83 hey
17-11-17_14:19:07    23440 iflyweb 20 0 20.765g 0.010t 3048 S 193.3 32.1 8:35.52 hey
17-11-17_14:19:08    23440 iflyweb 20 0 20.765g 0.010t 3048 S 206.7 32.2 8:38.06 hey
...
```

and the `hey` process would be killed by system after about 2 or 3 hours. Is it caused by memory leaks?

**Comment by mdakin** [comment]
+ @rakyll 

In short, yes.

When hey sends gots a response, it adds certain metrics to many lists here:
https://github.com/rakyll/hey/blob/master/requester/print.go#L76

Because we never flush these lists, in time they get bigger and bigger. The solution would probably be incrementally update the stats when these lists reach a certain size. Especially on long standing connections to a fast server hey memory usage increases quite fast.

I will try to see if I can introduce a fix.

**Comment by mdakin** [comment]
Actually the real reason is a bit different, we have a channel with capacity N that we write results into. Because this channel is never emptied until the reporting happens, which is when all requests are done, it continues to accumulate report records in its internal buffer. 

Note: My go knowledge is quite poor, and I do not remember much about channel semantics and subtleties, but this is probably the actual reason.

```
func (b *Work) Run() {
...
	b.results = make(chan *result, b.N)  // <--- Results channel is created here 
	b.stopCh = make(chan struct{}, 1000)
	b.start = time.Now()

	b.runWorkers() // <--- Results are added to channel
	b.Finish()
}

func (b *Work) Finish() {
	b.stopCh <- struct{}{}
	close(b.results)   <--- Channel is closed here
	total := time.Now().Sub(b.start)
	newReport(b.writer(), b.N, b.results, b.Output, total).finalize()  <-- reads channel, prints report
}
```

**Comment by psy-core** [comment]
I knew it. Thanks a lot. :)

**Comment by mdakin** [comment]
Lets keep it open until there is a solution in place.

**Comment by mdakin** [comment]
@psy-core (FYI @rakyll )

To solve this problem, we need a few things:

1. The code semantics should change from "Prepare report after everything is done" to "Update report data as the data streams in" 

2. To have a continuously updating system, we need a different histogram algorithm. We can use a streaming (online) histogram algorithm that can adaptively change bucket ranges, something like this:
https://github.com/VividCortex/gohistogram/blob/master/numerichistogram.go

3. Although NumericHistogram class is nice and offers methods to extract approximate quantiles , its default histogram graph is kinda ugly especially if we want to choose higher bucket counts to get more granular latency quantiles. So we probably want to fork it and change it.

Alternatively, we can use a largish result channel e.g. min(N, 10000)  and determine the histogram bucket intervals when this buffer is full and create an overflow bucket if some oddball value comes in later. But this would make calculating latency quantiles tricky.

In general I think this bug is important, I am not happy with Hey using a lot of memory memory when N is big and grow boundlessly as well. It should have a a small memory footprint.

Unfortunately I don't have much time to work on this, so I would be happy if someone with more go experience would help.

**Comment by mdakin** [comment]
@psy-core Note that the solution in #74 is a bit different than what I described in the previous comment, we now limit the number of results for histogram and latency calculations, though not perfect this is a much simpler solution, and still gives results for the first 1million responses which should be fine for most tasks.
Now hey will not consume more than ~100MB memory even for long running tasks..
